/*
 * This file is generated by jOOQ.
*/
package com.platform.chorus.database.tables.pojos;


import java.io.Serializable;
import java.util.Arrays;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Entity implements Serializable {

    private static final long serialVersionUID = -812246876;

    private Integer   id;
    private String    name;
    private String    class_;
    private String    creator;
    private String[]  tags;
    private Integer[] contains;
    private String    description;

    public Entity() {}

    public Entity(Entity value) {
        this.id = value.id;
        this.name = value.name;
        this.class_ = value.class_;
        this.creator = value.creator;
        this.tags = value.tags;
        this.contains = value.contains;
        this.description = value.description;
    }

    public Entity(
        Integer   id,
        String    name,
        String    class_,
        String    creator,
        String[]  tags,
        Integer[] contains,
        String    description
    ) {
        this.id = id;
        this.name = name;
        this.class_ = class_;
        this.creator = creator;
        this.tags = tags;
        this.contains = contains;
        this.description = description;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getClass_() {
        return this.class_;
    }

    public void setClass_(String class_) {
        this.class_ = class_;
    }

    public String getCreator() {
        return this.creator;
    }

    public void setCreator(String creator) {
        this.creator = creator;
    }

    public String[] getTags() {
        return this.tags;
    }

    public void setTags(String... tags) {
        this.tags = tags;
    }

    public Integer[] getContains() {
        return this.contains;
    }

    public void setContains(Integer... contains) {
        this.contains = contains;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Entity (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(class_);
        sb.append(", ").append(creator);
        sb.append(", ").append(Arrays.toString(tags));
        sb.append(", ").append(Arrays.toString(contains));
        sb.append(", ").append(description);

        sb.append(")");
        return sb.toString();
    }
}
