/*
 * This file is generated by jOOQ.
*/
package com.platform.chorus.database.tables.pojos;


import java.io.Serializable;
import java.util.Arrays;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ItemInstance implements Serializable {

    private static final long serialVersionUID = -1258195591;

    private Integer   oid;
    private String    type;
    private Object    content;
    private Integer[] refs;
    private String[]  tags;

    public ItemInstance() {}

    public ItemInstance(ItemInstance value) {
        this.oid = value.oid;
        this.type = value.type;
        this.content = value.content;
        this.refs = value.refs;
        this.tags = value.tags;
    }

    public ItemInstance(
        Integer   oid,
        String    type,
        Object    content,
        Integer[] refs,
        String[]  tags
    ) {
        this.oid = oid;
        this.type = type;
        this.content = content;
        this.refs = refs;
        this.tags = tags;
    }

    public Integer getOid() {
        return this.oid;
    }

    public void setOid(Integer oid) {
        this.oid = oid;
    }

    public String getType() {
        return this.type;
    }

    public void setType(String type) {
        this.type = type;
    }


    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using <deprecationOnUnknownTypes/> in your code generator configuration.
     */
    @java.lang.Deprecated
    public Object getContent() {
        return this.content;
    }


    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using <deprecationOnUnknownTypes/> in your code generator configuration.
     */
    @java.lang.Deprecated
    public void setContent(Object content) {
        this.content = content;
    }

    public Integer[] getRefs() {
        return this.refs;
    }

    public void setRefs(Integer... refs) {
        this.refs = refs;
    }

    public String[] getTags() {
        return this.tags;
    }

    public void setTags(String... tags) {
        this.tags = tags;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ItemInstance (");

        sb.append(oid);
        sb.append(", ").append(type);
        sb.append(", ").append(content);
        sb.append(", ").append(Arrays.toString(refs));
        sb.append(", ").append(Arrays.toString(tags));

        sb.append(")");
        return sb.toString();
    }
}
