/*
 * This file is generated by jOOQ.
*/
package com.platform.chorus.database.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MetaRelation implements Serializable {

    private static final long serialVersionUID = -1519464338;

    private String  type;
    private Integer sid;
    private Integer tid;

    public MetaRelation() {}

    public MetaRelation(MetaRelation value) {
        this.type = value.type;
        this.sid = value.sid;
        this.tid = value.tid;
    }

    public MetaRelation(
        String  type,
        Integer sid,
        Integer tid
    ) {
        this.type = type;
        this.sid = sid;
        this.tid = tid;
    }

    public String getType() {
        return this.type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public Integer getSid() {
        return this.sid;
    }

    public void setSid(Integer sid) {
        this.sid = sid;
    }

    public Integer getTid() {
        return this.tid;
    }

    public void setTid(Integer tid) {
        this.tid = tid;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("MetaRelation (");

        sb.append(type);
        sb.append(", ").append(sid);
        sb.append(", ").append(tid);

        sb.append(")");
        return sb.toString();
    }
}
