/*
 * This file is generated by jOOQ.
*/
package com.platform.chorus.database.tables.pojos;


import java.io.Serializable;
import java.util.Arrays;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MetaClass implements Serializable {

    private static final long serialVersionUID = -1846926007;

    private Integer   cid;
    private String    package_;
    private String    name;
    private Integer[] extends_;
    private String    modifier;
    private String    scope;
    private String    description;

    public MetaClass() {}

    public MetaClass(MetaClass value) {
        this.cid = value.cid;
        this.package_ = value.package_;
        this.name = value.name;
        this.extends_ = value.extends_;
        this.modifier = value.modifier;
        this.scope = value.scope;
        this.description = value.description;
    }

    public MetaClass(
        Integer   cid,
        String    package_,
        String    name,
        Integer[] extends_,
        String    modifier,
        String    scope,
        String    description
    ) {
        this.cid = cid;
        this.package_ = package_;
        this.name = name;
        this.extends_ = extends_;
        this.modifier = modifier;
        this.scope = scope;
        this.description = description;
    }

    public Integer getCid() {
        return this.cid;
    }

    public void setCid(Integer cid) {
        this.cid = cid;
    }

    public String getPackage() {
        return this.package_;
    }

    public void setPackage(String package_) {
        this.package_ = package_;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Integer[] getExtends() {
        return this.extends_;
    }

    public void setExtends(Integer... extends_) {
        this.extends_ = extends_;
    }

    public String getModifier() {
        return this.modifier;
    }

    public void setModifier(String modifier) {
        this.modifier = modifier;
    }

    public String getScope() {
        return this.scope;
    }

    public void setScope(String scope) {
        this.scope = scope;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("MetaClass (");

        sb.append(cid);
        sb.append(", ").append(package_);
        sb.append(", ").append(name);
        sb.append(", ").append(Arrays.toString(extends_));
        sb.append(", ").append(modifier);
        sb.append(", ").append(scope);
        sb.append(", ").append(description);

        sb.append(")");
        return sb.toString();
    }
}
