/*
 * This file is generated by jOOQ.
*/
package com.platform.chorus.database.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MetaField implements Serializable {

    private static final long serialVersionUID = -1488917222;

    private Integer fid;
    private String  name;
    private String  type;
    private Integer owner;
    private String  default_;
    private String  unit;
    private String  range;
    private Boolean optional;
    private String  format;
    private String  description;

    public MetaField() {}

    public MetaField(MetaField value) {
        this.fid = value.fid;
        this.name = value.name;
        this.type = value.type;
        this.owner = value.owner;
        this.default_ = value.default_;
        this.unit = value.unit;
        this.range = value.range;
        this.optional = value.optional;
        this.format = value.format;
        this.description = value.description;
    }

    public MetaField(
        Integer fid,
        String  name,
        String  type,
        Integer owner,
        String  default_,
        String  unit,
        String  range,
        Boolean optional,
        String  format,
        String  description
    ) {
        this.fid = fid;
        this.name = name;
        this.type = type;
        this.owner = owner;
        this.default_ = default_;
        this.unit = unit;
        this.range = range;
        this.optional = optional;
        this.format = format;
        this.description = description;
    }

    public Integer getFid() {
        return this.fid;
    }

    public void setFid(Integer fid) {
        this.fid = fid;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getType() {
        return this.type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public Integer getOwner() {
        return this.owner;
    }

    public void setOwner(Integer owner) {
        this.owner = owner;
    }

    public String getDefault() {
        return this.default_;
    }

    public void setDefault(String default_) {
        this.default_ = default_;
    }

    public String getUnit() {
        return this.unit;
    }

    public void setUnit(String unit) {
        this.unit = unit;
    }

    public String getRange() {
        return this.range;
    }

    public void setRange(String range) {
        this.range = range;
    }

    public Boolean getOptional() {
        return this.optional;
    }

    public void setOptional(Boolean optional) {
        this.optional = optional;
    }

    public String getFormat() {
        return this.format;
    }

    public void setFormat(String format) {
        this.format = format;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("MetaField (");

        sb.append(fid);
        sb.append(", ").append(name);
        sb.append(", ").append(type);
        sb.append(", ").append(owner);
        sb.append(", ").append(default_);
        sb.append(", ").append(unit);
        sb.append(", ").append(range);
        sb.append(", ").append(optional);
        sb.append(", ").append(format);
        sb.append(", ").append(description);

        sb.append(")");
        return sb.toString();
    }
}
