/*
 * This file is generated by jOOQ.
*/
package com.platform.chorus.database.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MetaMethod implements Serializable {

    private static final long serialVersionUID = 1240767847;

    private Integer mid;
    private String  name;
    private String  result;
    private String  argument;
    private Integer owner;
    private String  description;

    public MetaMethod() {}

    public MetaMethod(MetaMethod value) {
        this.mid = value.mid;
        this.name = value.name;
        this.result = value.result;
        this.argument = value.argument;
        this.owner = value.owner;
        this.description = value.description;
    }

    public MetaMethod(
        Integer mid,
        String  name,
        String  result,
        String  argument,
        Integer owner,
        String  description
    ) {
        this.mid = mid;
        this.name = name;
        this.result = result;
        this.argument = argument;
        this.owner = owner;
        this.description = description;
    }

    public Integer getMid() {
        return this.mid;
    }

    public void setMid(Integer mid) {
        this.mid = mid;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getResult() {
        return this.result;
    }

    public void setResult(String result) {
        this.result = result;
    }

    public String getArgument() {
        return this.argument;
    }

    public void setArgument(String argument) {
        this.argument = argument;
    }

    public Integer getOwner() {
        return this.owner;
    }

    public void setOwner(Integer owner) {
        this.owner = owner;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("MetaMethod (");

        sb.append(mid);
        sb.append(", ").append(name);
        sb.append(", ").append(result);
        sb.append(", ").append(argument);
        sb.append(", ").append(owner);
        sb.append(", ").append(description);

        sb.append(")");
        return sb.toString();
    }
}
