/*
 * This file is generated by jOOQ.
*/
package com.platform.chorus.db.tables.records;


import com.platform.chorus.db.tables.FieldModel;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record15;
import org.jooq.Row15;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FieldModelRecord extends UpdatableRecordImpl<FieldModelRecord> implements Record15<Integer, String, String, String, String, String, String, String, String, Boolean, Boolean, Boolean, String, Integer, String> {

    private static final long serialVersionUID = 1728920574;

    /**
     * Setter for <code>public.field_model.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.field_model.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.field_model.owner</code>.
     */
    public void setOwner(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.field_model.owner</code>.
     */
    public String getOwner() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.field_model.name</code>.
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.field_model.name</code>.
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.field_model.type</code>.
     */
    public void setType(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.field_model.type</code>.
     */
    public String getType() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.field_model.label</code>.
     */
    public void setLabel(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.field_model.label</code>.
     */
    public String getLabel() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.field_model.unit</code>.
     */
    public void setUnit(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.field_model.unit</code>.
     */
    public String getUnit() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.field_model.range</code>.
     */
    public void setRange(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.field_model.range</code>.
     */
    public String getRange() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.field_model.default</code>.
     */
    public void setDefault(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.field_model.default</code>.
     */
    public String getDefault() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.field_model.format</code>.
     */
    public void setFormat(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.field_model.format</code>.
     */
    public String getFormat() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.field_model.optional</code>.
     */
    public void setOptional(Boolean value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.field_model.optional</code>.
     */
    public Boolean getOptional() {
        return (Boolean) get(9);
    }

    /**
     * Setter for <code>public.field_model.configurable</code>.
     */
    public void setConfigurable(Boolean value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.field_model.configurable</code>.
     */
    public Boolean getConfigurable() {
        return (Boolean) get(10);
    }

    /**
     * Setter for <code>public.field_model.collectible</code>.
     */
    public void setCollectible(Boolean value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.field_model.collectible</code>.
     */
    public Boolean getCollectible() {
        return (Boolean) get(11);
    }

    /**
     * Setter for <code>public.field_model.collector</code>.
     */
    public void setCollector(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.field_model.collector</code>.
     */
    public String getCollector() {
        return (String) get(12);
    }

    /**
     * Setter for <code>public.field_model.interval</code>.
     */
    public void setInterval(Integer value) {
        set(13, value);
    }

    /**
     * Getter for <code>public.field_model.interval</code>.
     */
    public Integer getInterval() {
        return (Integer) get(13);
    }

    /**
     * Setter for <code>public.field_model.description</code>.
     */
    public void setDescription(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>public.field_model.description</code>.
     */
    public String getDescription() {
        return (String) get(14);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record15 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row15<Integer, String, String, String, String, String, String, String, String, Boolean, Boolean, Boolean, String, Integer, String> fieldsRow() {
        return (Row15) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row15<Integer, String, String, String, String, String, String, String, String, Boolean, Boolean, Boolean, String, Integer, String> valuesRow() {
        return (Row15) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return FieldModel.FIELD_MODEL.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return FieldModel.FIELD_MODEL.OWNER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return FieldModel.FIELD_MODEL.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return FieldModel.FIELD_MODEL.TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return FieldModel.FIELD_MODEL.LABEL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return FieldModel.FIELD_MODEL.UNIT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return FieldModel.FIELD_MODEL.RANGE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return FieldModel.FIELD_MODEL.DEFAULT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return FieldModel.FIELD_MODEL.FORMAT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field10() {
        return FieldModel.FIELD_MODEL.OPTIONAL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field11() {
        return FieldModel.FIELD_MODEL.CONFIGURABLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field12() {
        return FieldModel.FIELD_MODEL.COLLECTIBLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field13() {
        return FieldModel.FIELD_MODEL.COLLECTOR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field14() {
        return FieldModel.FIELD_MODEL.INTERVAL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field15() {
        return FieldModel.FIELD_MODEL.DESCRIPTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getOwner();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getLabel();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getUnit();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getRange();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getDefault();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getFormat();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component10() {
        return getOptional();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component11() {
        return getConfigurable();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component12() {
        return getCollectible();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component13() {
        return getCollector();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component14() {
        return getInterval();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component15() {
        return getDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getOwner();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getLabel();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getUnit();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getRange();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getDefault();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getFormat();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value10() {
        return getOptional();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value11() {
        return getConfigurable();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value12() {
        return getCollectible();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value13() {
        return getCollector();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value14() {
        return getInterval();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value15() {
        return getDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FieldModelRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FieldModelRecord value2(String value) {
        setOwner(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FieldModelRecord value3(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FieldModelRecord value4(String value) {
        setType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FieldModelRecord value5(String value) {
        setLabel(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FieldModelRecord value6(String value) {
        setUnit(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FieldModelRecord value7(String value) {
        setRange(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FieldModelRecord value8(String value) {
        setDefault(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FieldModelRecord value9(String value) {
        setFormat(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FieldModelRecord value10(Boolean value) {
        setOptional(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FieldModelRecord value11(Boolean value) {
        setConfigurable(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FieldModelRecord value12(Boolean value) {
        setCollectible(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FieldModelRecord value13(String value) {
        setCollector(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FieldModelRecord value14(Integer value) {
        setInterval(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FieldModelRecord value15(String value) {
        setDescription(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FieldModelRecord values(Integer value1, String value2, String value3, String value4, String value5, String value6, String value7, String value8, String value9, Boolean value10, Boolean value11, Boolean value12, String value13, Integer value14, String value15) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FieldModelRecord
     */
    public FieldModelRecord() {
        super(FieldModel.FIELD_MODEL);
    }

    /**
     * Create a detached, initialised FieldModelRecord
     */
    public FieldModelRecord(Integer id, String owner, String name, String type, String label, String unit, String range, String default_, String format, Boolean optional, Boolean configurable, Boolean collectible, String collector, Integer interval, String description) {
        super(FieldModel.FIELD_MODEL);

        set(0, id);
        set(1, owner);
        set(2, name);
        set(3, type);
        set(4, label);
        set(5, unit);
        set(6, range);
        set(7, default_);
        set(8, format);
        set(9, optional);
        set(10, configurable);
        set(11, collectible);
        set(12, collector);
        set(13, interval);
        set(14, description);
    }
}
