/*
 * This file is generated by jOOQ.
*/
package com.platform.chorus.db.tables.records;


import com.platform.chorus.db.tables.ItemValue;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ItemValueRecord extends UpdatableRecordImpl<ItemValueRecord> implements Record5<Integer, String, String, String, String> {

    private static final long serialVersionUID = -2000505808;

    /**
     * Setter for <code>public.item_value.owner</code>.
     */
    public void setOwner(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.item_value.owner</code>.
     */
    public Integer getOwner() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.item_value.type</code>.
     */
    public void setType(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.item_value.type</code>.
     */
    public String getType() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.item_value.prototype</code>.
     */
    public void setPrototype(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.item_value.prototype</code>.
     */
    public String getPrototype() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.item_value.creator</code>.
     */
    public void setCreator(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.item_value.creator</code>.
     */
    public String getCreator() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.item_value.description</code>.
     */
    public void setDescription(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.item_value.description</code>.
     */
    public String getDescription() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, String, String, String, String> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, String, String, String, String> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return ItemValue.ITEM_VALUE.OWNER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return ItemValue.ITEM_VALUE.TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return ItemValue.ITEM_VALUE.PROTOTYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return ItemValue.ITEM_VALUE.CREATOR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return ItemValue.ITEM_VALUE.DESCRIPTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getOwner();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getPrototype();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getCreator();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getOwner();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getPrototype();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getCreator();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ItemValueRecord value1(Integer value) {
        setOwner(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ItemValueRecord value2(String value) {
        setType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ItemValueRecord value3(String value) {
        setPrototype(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ItemValueRecord value4(String value) {
        setCreator(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ItemValueRecord value5(String value) {
        setDescription(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ItemValueRecord values(Integer value1, String value2, String value3, String value4, String value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ItemValueRecord
     */
    public ItemValueRecord() {
        super(ItemValue.ITEM_VALUE);
    }

    /**
     * Create a detached, initialised ItemValueRecord
     */
    public ItemValueRecord(Integer owner, String type, String prototype, String creator, String description) {
        super(ItemValue.ITEM_VALUE);

        set(0, owner);
        set(1, type);
        set(2, prototype);
        set(3, creator);
        set(4, description);
    }
}
