/*
 * This file is generated by jOOQ.
*/
package com.platform.chorus.database;


import com.platform.chorus.database.tables.ClassModel;
import com.platform.chorus.database.tables.Collector;
import com.platform.chorus.database.tables.Entity;
import com.platform.chorus.database.tables.FieldModel;
import com.platform.chorus.database.tables.Value;
import com.platform.chorus.database.tables.records.ClassModelRecord;
import com.platform.chorus.database.tables.records.CollectorRecord;
import com.platform.chorus.database.tables.records.EntityRecord;
import com.platform.chorus.database.tables.records.FieldModelRecord;
import com.platform.chorus.database.tables.records.ValueRecord;

import javax.annotation.Generated;

import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<ClassModelRecord, Integer> IDENTITY_CLASS_MODEL = Identities0.IDENTITY_CLASS_MODEL;
    public static final Identity<EntityRecord, Integer> IDENTITY_ENTITY = Identities0.IDENTITY_ENTITY;
    public static final Identity<FieldModelRecord, Integer> IDENTITY_FIELD_MODEL = Identities0.IDENTITY_FIELD_MODEL;
    public static final Identity<ValueRecord, Integer> IDENTITY_VALUE = Identities0.IDENTITY_VALUE;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<ClassModelRecord> CLASS_MODEL_PKEY = UniqueKeys0.CLASS_MODEL_PKEY;
    public static final UniqueKey<ClassModelRecord> CL_U_KEY = UniqueKeys0.CL_U_KEY;
    public static final UniqueKey<CollectorRecord> COLLECTOR_PKEY = UniqueKeys0.COLLECTOR_PKEY;
    public static final UniqueKey<EntityRecord> ENTITY_PKEY = UniqueKeys0.ENTITY_PKEY;
    public static final UniqueKey<FieldModelRecord> FIELD_MODEL_PKEY = UniqueKeys0.FIELD_MODEL_PKEY;
    public static final UniqueKey<FieldModelRecord> FD_U_KEY = UniqueKeys0.FD_U_KEY;
    public static final UniqueKey<ValueRecord> VALUE_PKEY = UniqueKeys0.VALUE_PKEY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<ClassModelRecord, Integer> IDENTITY_CLASS_MODEL = Internal.createIdentity(ClassModel.CLASS_MODEL, ClassModel.CLASS_MODEL.ID);
        public static Identity<EntityRecord, Integer> IDENTITY_ENTITY = Internal.createIdentity(Entity.ENTITY, Entity.ENTITY.ID);
        public static Identity<FieldModelRecord, Integer> IDENTITY_FIELD_MODEL = Internal.createIdentity(FieldModel.FIELD_MODEL, FieldModel.FIELD_MODEL.ID);
        public static Identity<ValueRecord, Integer> IDENTITY_VALUE = Internal.createIdentity(Value.VALUE, Value.VALUE.OWNER);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<ClassModelRecord> CLASS_MODEL_PKEY = Internal.createUniqueKey(ClassModel.CLASS_MODEL, "class_model_pkey", ClassModel.CLASS_MODEL.ID);
        public static final UniqueKey<ClassModelRecord> CL_U_KEY = Internal.createUniqueKey(ClassModel.CLASS_MODEL, "cl_u_key", ClassModel.CLASS_MODEL.PACKAGE, ClassModel.CLASS_MODEL.NAME);
        public static final UniqueKey<CollectorRecord> COLLECTOR_PKEY = Internal.createUniqueKey(Collector.COLLECTOR, "collector_pkey", Collector.COLLECTOR.NAME);
        public static final UniqueKey<EntityRecord> ENTITY_PKEY = Internal.createUniqueKey(Entity.ENTITY, "entity_pkey", Entity.ENTITY.ID);
        public static final UniqueKey<FieldModelRecord> FIELD_MODEL_PKEY = Internal.createUniqueKey(FieldModel.FIELD_MODEL, "field_model_pkey", FieldModel.FIELD_MODEL.ID);
        public static final UniqueKey<FieldModelRecord> FD_U_KEY = Internal.createUniqueKey(FieldModel.FIELD_MODEL, "fd_u_key", FieldModel.FIELD_MODEL.OWNER, FieldModel.FIELD_MODEL.NAME);
        public static final UniqueKey<ValueRecord> VALUE_PKEY = Internal.createUniqueKey(Value.VALUE, "value_pkey", Value.VALUE.OWNER);
    }
}
