/*
 * This file is generated by jOOQ.
*/
package com.platform.chorus.db;


import com.platform.chorus.db.tables.ClassModel;
import com.platform.chorus.db.tables.Collector;
import com.platform.chorus.db.tables.Entity;
import com.platform.chorus.db.tables.FieldModel;
import com.platform.chorus.db.tables.Relationship;
import com.platform.chorus.db.tables.Value;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = -43298080;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.class_model</code>.
     */
    public final ClassModel CLASS_MODEL = com.platform.chorus.db.tables.ClassModel.CLASS_MODEL;

    /**
     * The table <code>public.collector</code>.
     */
    public final Collector COLLECTOR = com.platform.chorus.db.tables.Collector.COLLECTOR;

    /**
     * The table <code>public.entity</code>.
     */
    public final Entity ENTITY = com.platform.chorus.db.tables.Entity.ENTITY;

    /**
     * The table <code>public.field_model</code>.
     */
    public final FieldModel FIELD_MODEL = com.platform.chorus.db.tables.FieldModel.FIELD_MODEL;

    /**
     * The table <code>public.relationship</code>.
     */
    public final Relationship RELATIONSHIP = com.platform.chorus.db.tables.Relationship.RELATIONSHIP;

    /**
     * The table <code>public.value</code>.
     */
    public final Value VALUE = com.platform.chorus.db.tables.Value.VALUE;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            ClassModel.CLASS_MODEL,
            Collector.COLLECTOR,
            Entity.ENTITY,
            FieldModel.FIELD_MODEL,
            Relationship.RELATIONSHIP,
            Value.VALUE);
    }
}
