/*
 * This file is generated by jOOQ.
*/
package com.platform.chorus.database.tables.daos;


import com.platform.chorus.database.tables.ItemInstance;
import com.platform.chorus.database.tables.records.ItemInstanceRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ItemInstanceDao extends DAOImpl<ItemInstanceRecord, com.platform.chorus.database.tables.pojos.ItemInstance, Integer> {

    /**
     * Create a new ItemInstanceDao without any configuration
     */
    public ItemInstanceDao() {
        super(ItemInstance.ITEM_INSTANCE, com.platform.chorus.database.tables.pojos.ItemInstance.class);
    }

    /**
     * Create a new ItemInstanceDao with an attached configuration
     */
    public ItemInstanceDao(Configuration configuration) {
        super(ItemInstance.ITEM_INSTANCE, com.platform.chorus.database.tables.pojos.ItemInstance.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(com.platform.chorus.database.tables.pojos.ItemInstance object) {
        return object.getOid();
    }

    /**
     * Fetch records that have <code>oid IN (values)</code>
     */
    public List<com.platform.chorus.database.tables.pojos.ItemInstance> fetchByOid(Integer... values) {
        return fetch(ItemInstance.ITEM_INSTANCE.OID, values);
    }

    /**
     * Fetch a unique record that has <code>oid = value</code>
     */
    public com.platform.chorus.database.tables.pojos.ItemInstance fetchOneByOid(Integer value) {
        return fetchOne(ItemInstance.ITEM_INSTANCE.OID, value);
    }

    /**
     * Fetch records that have <code>type IN (values)</code>
     */
    public List<com.platform.chorus.database.tables.pojos.ItemInstance> fetchByType(String... values) {
        return fetch(ItemInstance.ITEM_INSTANCE.TYPE, values);
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be turned off using <deprecationOnUnknownTypes/> in your code generator configuration.
     */
    @java.lang.Deprecated
    public List<com.platform.chorus.database.tables.pojos.ItemInstance> fetchByContent(Object... values) {
        return fetch(ItemInstance.ITEM_INSTANCE.CONTENT, values);
    }

    /**
     * Fetch records that have <code>refs IN (values)</code>
     */
    public List<com.platform.chorus.database.tables.pojos.ItemInstance> fetchByRefs(Integer[]... values) {
        return fetch(ItemInstance.ITEM_INSTANCE.REFS, values);
    }

    /**
     * Fetch records that have <code>tags IN (values)</code>
     */
    public List<com.platform.chorus.database.tables.pojos.ItemInstance> fetchByTags(String[]... values) {
        return fetch(ItemInstance.ITEM_INSTANCE.TAGS, values);
    }
}
