/*
 * This file is generated by jOOQ.
*/
package com.platform.chorus.database.tables.daos;


import com.platform.chorus.database.tables.MetaMethod;
import com.platform.chorus.database.tables.records.MetaMethodRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MetaMethodDao extends DAOImpl<MetaMethodRecord, com.platform.chorus.database.tables.pojos.MetaMethod, Integer> {

    /**
     * Create a new MetaMethodDao without any configuration
     */
    public MetaMethodDao() {
        super(MetaMethod.META_METHOD, com.platform.chorus.database.tables.pojos.MetaMethod.class);
    }

    /**
     * Create a new MetaMethodDao with an attached configuration
     */
    public MetaMethodDao(Configuration configuration) {
        super(MetaMethod.META_METHOD, com.platform.chorus.database.tables.pojos.MetaMethod.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(com.platform.chorus.database.tables.pojos.MetaMethod object) {
        return object.getMid();
    }

    /**
     * Fetch records that have <code>mid IN (values)</code>
     */
    public List<com.platform.chorus.database.tables.pojos.MetaMethod> fetchByMid(Integer... values) {
        return fetch(MetaMethod.META_METHOD.MID, values);
    }

    /**
     * Fetch a unique record that has <code>mid = value</code>
     */
    public com.platform.chorus.database.tables.pojos.MetaMethod fetchOneByMid(Integer value) {
        return fetchOne(MetaMethod.META_METHOD.MID, value);
    }

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    public List<com.platform.chorus.database.tables.pojos.MetaMethod> fetchByName(String... values) {
        return fetch(MetaMethod.META_METHOD.NAME, values);
    }

    /**
     * Fetch records that have <code>result IN (values)</code>
     */
    public List<com.platform.chorus.database.tables.pojos.MetaMethod> fetchByResult(String... values) {
        return fetch(MetaMethod.META_METHOD.RESULT, values);
    }

    /**
     * Fetch records that have <code>argument IN (values)</code>
     */
    public List<com.platform.chorus.database.tables.pojos.MetaMethod> fetchByArgument(String... values) {
        return fetch(MetaMethod.META_METHOD.ARGUMENT, values);
    }

    /**
     * Fetch records that have <code>owner IN (values)</code>
     */
    public List<com.platform.chorus.database.tables.pojos.MetaMethod> fetchByOwner(Integer... values) {
        return fetch(MetaMethod.META_METHOD.OWNER, values);
    }

    /**
     * Fetch records that have <code>description IN (values)</code>
     */
    public List<com.platform.chorus.database.tables.pojos.MetaMethod> fetchByDescription(String... values) {
        return fetch(MetaMethod.META_METHOD.DESCRIPTION, values);
    }
}
