/*
 * This file is generated by jOOQ.
*/
package com.platform.chorus.database.tables.daos;


import com.platform.chorus.database.tables.MetaClass;
import com.platform.chorus.database.tables.records.MetaClassRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MetaClassDao extends DAOImpl<MetaClassRecord, com.platform.chorus.database.tables.pojos.MetaClass, Integer> {

    /**
     * Create a new MetaClassDao without any configuration
     */
    public MetaClassDao() {
        super(MetaClass.META_CLASS, com.platform.chorus.database.tables.pojos.MetaClass.class);
    }

    /**
     * Create a new MetaClassDao with an attached configuration
     */
    public MetaClassDao(Configuration configuration) {
        super(MetaClass.META_CLASS, com.platform.chorus.database.tables.pojos.MetaClass.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(com.platform.chorus.database.tables.pojos.MetaClass object) {
        return object.getCid();
    }

    /**
     * Fetch records that have <code>cid IN (values)</code>
     */
    public List<com.platform.chorus.database.tables.pojos.MetaClass> fetchByCid(Integer... values) {
        return fetch(MetaClass.META_CLASS.CID, values);
    }

    /**
     * Fetch a unique record that has <code>cid = value</code>
     */
    public com.platform.chorus.database.tables.pojos.MetaClass fetchOneByCid(Integer value) {
        return fetchOne(MetaClass.META_CLASS.CID, value);
    }

    /**
     * Fetch records that have <code>package IN (values)</code>
     */
    public List<com.platform.chorus.database.tables.pojos.MetaClass> fetchByPackage(String... values) {
        return fetch(MetaClass.META_CLASS.PACKAGE, values);
    }

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    public List<com.platform.chorus.database.tables.pojos.MetaClass> fetchByName(String... values) {
        return fetch(MetaClass.META_CLASS.NAME, values);
    }

    /**
     * Fetch records that have <code>extends IN (values)</code>
     */
    public List<com.platform.chorus.database.tables.pojos.MetaClass> fetchByExtends(Integer[]... values) {
        return fetch(MetaClass.META_CLASS.EXTENDS, values);
    }

    /**
     * Fetch records that have <code>modifier IN (values)</code>
     */
    public List<com.platform.chorus.database.tables.pojos.MetaClass> fetchByModifier(String... values) {
        return fetch(MetaClass.META_CLASS.MODIFIER, values);
    }

    /**
     * Fetch records that have <code>scope IN (values)</code>
     */
    public List<com.platform.chorus.database.tables.pojos.MetaClass> fetchByScope(String... values) {
        return fetch(MetaClass.META_CLASS.SCOPE, values);
    }

    /**
     * Fetch records that have <code>description IN (values)</code>
     */
    public List<com.platform.chorus.database.tables.pojos.MetaClass> fetchByDescription(String... values) {
        return fetch(MetaClass.META_CLASS.DESCRIPTION, values);
    }
}
