/*
 * This file is generated by jOOQ.
*/
package com.platform.chorus.database.tables.daos;


import com.platform.chorus.database.tables.MetaField;
import com.platform.chorus.database.tables.records.MetaFieldRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MetaFieldDao extends DAOImpl<MetaFieldRecord, com.platform.chorus.database.tables.pojos.MetaField, Integer> {

    /**
     * Create a new MetaFieldDao without any configuration
     */
    public MetaFieldDao() {
        super(MetaField.META_FIELD, com.platform.chorus.database.tables.pojos.MetaField.class);
    }

    /**
     * Create a new MetaFieldDao with an attached configuration
     */
    public MetaFieldDao(Configuration configuration) {
        super(MetaField.META_FIELD, com.platform.chorus.database.tables.pojos.MetaField.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(com.platform.chorus.database.tables.pojos.MetaField object) {
        return object.getFid();
    }

    /**
     * Fetch records that have <code>fid IN (values)</code>
     */
    public List<com.platform.chorus.database.tables.pojos.MetaField> fetchByFid(Integer... values) {
        return fetch(MetaField.META_FIELD.FID, values);
    }

    /**
     * Fetch a unique record that has <code>fid = value</code>
     */
    public com.platform.chorus.database.tables.pojos.MetaField fetchOneByFid(Integer value) {
        return fetchOne(MetaField.META_FIELD.FID, value);
    }

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    public List<com.platform.chorus.database.tables.pojos.MetaField> fetchByName(String... values) {
        return fetch(MetaField.META_FIELD.NAME, values);
    }

    /**
     * Fetch records that have <code>type IN (values)</code>
     */
    public List<com.platform.chorus.database.tables.pojos.MetaField> fetchByType(String... values) {
        return fetch(MetaField.META_FIELD.TYPE, values);
    }

    /**
     * Fetch records that have <code>owner IN (values)</code>
     */
    public List<com.platform.chorus.database.tables.pojos.MetaField> fetchByOwner(Integer... values) {
        return fetch(MetaField.META_FIELD.OWNER, values);
    }

    /**
     * Fetch records that have <code>default IN (values)</code>
     */
    public List<com.platform.chorus.database.tables.pojos.MetaField> fetchByDefault(String... values) {
        return fetch(MetaField.META_FIELD.DEFAULT, values);
    }

    /**
     * Fetch records that have <code>unit IN (values)</code>
     */
    public List<com.platform.chorus.database.tables.pojos.MetaField> fetchByUnit(String... values) {
        return fetch(MetaField.META_FIELD.UNIT, values);
    }

    /**
     * Fetch records that have <code>range IN (values)</code>
     */
    public List<com.platform.chorus.database.tables.pojos.MetaField> fetchByRange(String... values) {
        return fetch(MetaField.META_FIELD.RANGE, values);
    }

    /**
     * Fetch records that have <code>optional IN (values)</code>
     */
    public List<com.platform.chorus.database.tables.pojos.MetaField> fetchByOptional(Boolean... values) {
        return fetch(MetaField.META_FIELD.OPTIONAL, values);
    }

    /**
     * Fetch records that have <code>format IN (values)</code>
     */
    public List<com.platform.chorus.database.tables.pojos.MetaField> fetchByFormat(String... values) {
        return fetch(MetaField.META_FIELD.FORMAT, values);
    }

    /**
     * Fetch records that have <code>description IN (values)</code>
     */
    public List<com.platform.chorus.database.tables.pojos.MetaField> fetchByDescription(String... values) {
        return fetch(MetaField.META_FIELD.DESCRIPTION, values);
    }
}
