/*
 * This file is generated by jOOQ.
*/
package com.platform.chorus.database.tables.daos;


import com.platform.chorus.database.tables.Value;
import com.platform.chorus.database.tables.records.ValueRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ValueDao extends DAOImpl<ValueRecord, com.platform.chorus.database.tables.pojos.Value, Integer> {

    /**
     * Create a new ValueDao without any configuration
     */
    public ValueDao() {
        super(Value.VALUE, com.platform.chorus.database.tables.pojos.Value.class);
    }

    /**
     * Create a new ValueDao with an attached configuration
     */
    public ValueDao(Configuration configuration) {
        super(Value.VALUE, com.platform.chorus.database.tables.pojos.Value.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(com.platform.chorus.database.tables.pojos.Value object) {
        return object.getOwner();
    }

    /**
     * Fetch records that have <code>owner IN (values)</code>
     */
    public List<com.platform.chorus.database.tables.pojos.Value> fetchByOwner(Integer... values) {
        return fetch(Value.VALUE.OWNER, values);
    }

    /**
     * Fetch a unique record that has <code>owner = value</code>
     */
    public com.platform.chorus.database.tables.pojos.Value fetchOneByOwner(Integer value) {
        return fetchOne(Value.VALUE.OWNER, value);
    }

    /**
     * Fetch records that have <code>type IN (values)</code>
     */
    public List<com.platform.chorus.database.tables.pojos.Value> fetchByType(String... values) {
        return fetch(Value.VALUE.TYPE, values);
    }

    /**
     * Fetch records that have <code>class IN (values)</code>
     */
    public List<com.platform.chorus.database.tables.pojos.Value> fetchByClass(String... values) {
        return fetch(Value.VALUE.CLASS, values);
    }

    /**
     * Fetch records that have <code>creator IN (values)</code>
     */
    public List<com.platform.chorus.database.tables.pojos.Value> fetchByCreator(String... values) {
        return fetch(Value.VALUE.CREATOR, values);
    }

    /**
     * Fetch records that have <code>description IN (values)</code>
     */
    public List<com.platform.chorus.database.tables.pojos.Value> fetchByDescription(String... values) {
        return fetch(Value.VALUE.DESCRIPTION, values);
    }
}
