/*
 * This file is generated by jOOQ.
*/
package com.platform.chorus.db.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ItemValue implements Serializable {

    private static final long serialVersionUID = -718829733;

    private Integer owner;
    private String  type;
    private String  prototype;
    private String  creator;
    private String  description;

    public ItemValue() {}

    public ItemValue(ItemValue value) {
        this.owner = value.owner;
        this.type = value.type;
        this.prototype = value.prototype;
        this.creator = value.creator;
        this.description = value.description;
    }

    public ItemValue(
        Integer owner,
        String  type,
        String  prototype,
        String  creator,
        String  description
    ) {
        this.owner = owner;
        this.type = type;
        this.prototype = prototype;
        this.creator = creator;
        this.description = description;
    }

    public Integer getOwner() {
        return this.owner;
    }

    public void setOwner(Integer owner) {
        this.owner = owner;
    }

    public String getType() {
        return this.type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getPrototype() {
        return this.prototype;
    }

    public void setPrototype(String prototype) {
        this.prototype = prototype;
    }

    public String getCreator() {
        return this.creator;
    }

    public void setCreator(String creator) {
        this.creator = creator;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ItemValue (");

        sb.append(owner);
        sb.append(", ").append(type);
        sb.append(", ").append(prototype);
        sb.append(", ").append(creator);
        sb.append(", ").append(description);

        sb.append(")");
        return sb.toString();
    }
}
