/*
 * This file is generated by jOOQ.
*/
package com.platform.chorus.db.tables;


import com.platform.chorus.db.Public;
import com.platform.chorus.db.tables.records.RelationRecord;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Relation extends TableImpl<RelationRecord> {

    private static final long serialVersionUID = -1498527136;

    /**
     * The reference instance of <code>public.relation</code>
     */
    public static final Relation RELATION = new Relation();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RelationRecord> getRecordType() {
        return RelationRecord.class;
    }

    /**
     * The column <code>public.relation.sid</code>.
     */
    public final TableField<RelationRecord, Integer> SID = createField("sid", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.relation.tid</code>.
     */
    public final TableField<RelationRecord, Integer> TID = createField("tid", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.relation.type</code>.
     */
    public final TableField<RelationRecord, Integer> TYPE = createField("type", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * Create a <code>public.relation</code> table reference
     */
    public Relation() {
        this(DSL.name("relation"), null);
    }

    /**
     * Create an aliased <code>public.relation</code> table reference
     */
    public Relation(String alias) {
        this(DSL.name(alias), RELATION);
    }

    /**
     * Create an aliased <code>public.relation</code> table reference
     */
    public Relation(Name alias) {
        this(alias, RELATION);
    }

    private Relation(Name alias, Table<RelationRecord> aliased) {
        this(alias, aliased, null);
    }

    private Relation(Name alias, Table<RelationRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Relation as(String alias) {
        return new Relation(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Relation as(Name alias) {
        return new Relation(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Relation rename(String name) {
        return new Relation(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Relation rename(Name name) {
        return new Relation(name, null);
    }
}
