/*
 * This file is generated by jOOQ.
*/
package com.platform.chorus.db.tables;


import com.platform.chorus.db.Public;
import com.platform.chorus.db.tables.records.RelationshipRecord;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Relationship extends TableImpl<RelationshipRecord> {

    private static final long serialVersionUID = -1646818551;

    /**
     * The reference instance of <code>public.relationship</code>
     */
    public static final Relationship RELATIONSHIP = new Relationship();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RelationshipRecord> getRecordType() {
        return RelationshipRecord.class;
    }

    /**
     * The column <code>public.relationship.sid</code>.
     */
    public final TableField<RelationshipRecord, Integer> SID = createField("sid", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.relationship.tid</code>.
     */
    public final TableField<RelationshipRecord, Integer> TID = createField("tid", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.relationship.type</code>.
     */
    public final TableField<RelationshipRecord, Integer> TYPE = createField("type", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * Create a <code>public.relationship</code> table reference
     */
    public Relationship() {
        this(DSL.name("relationship"), null);
    }

    /**
     * Create an aliased <code>public.relationship</code> table reference
     */
    public Relationship(String alias) {
        this(DSL.name(alias), RELATIONSHIP);
    }

    /**
     * Create an aliased <code>public.relationship</code> table reference
     */
    public Relationship(Name alias) {
        this(alias, RELATIONSHIP);
    }

    private Relationship(Name alias, Table<RelationshipRecord> aliased) {
        this(alias, aliased, null);
    }

    private Relationship(Name alias, Table<RelationshipRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Relationship as(String alias) {
        return new Relationship(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Relationship as(Name alias) {
        return new Relationship(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Relationship rename(String name) {
        return new Relationship(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Relationship rename(Name name) {
        return new Relationship(name, null);
    }
}
