/*
 * This file is generated by jOOQ.
*/
package com.platform.chorus.db.tables.daos;


import com.platform.chorus.db.tables.ItemEntity;
import com.platform.chorus.db.tables.records.ItemEntityRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ItemEntityDao extends DAOImpl<ItemEntityRecord, com.platform.chorus.db.tables.pojos.ItemEntity, Integer> {

    /**
     * Create a new ItemEntityDao without any configuration
     */
    public ItemEntityDao() {
        super(ItemEntity.ITEM_ENTITY, com.platform.chorus.db.tables.pojos.ItemEntity.class);
    }

    /**
     * Create a new ItemEntityDao with an attached configuration
     */
    public ItemEntityDao(Configuration configuration) {
        super(ItemEntity.ITEM_ENTITY, com.platform.chorus.db.tables.pojos.ItemEntity.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(com.platform.chorus.db.tables.pojos.ItemEntity object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.platform.chorus.db.tables.pojos.ItemEntity> fetchById(Integer... values) {
        return fetch(ItemEntity.ITEM_ENTITY.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.platform.chorus.db.tables.pojos.ItemEntity fetchOneById(Integer value) {
        return fetchOne(ItemEntity.ITEM_ENTITY.ID, value);
    }

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    public List<com.platform.chorus.db.tables.pojos.ItemEntity> fetchByName(String... values) {
        return fetch(ItemEntity.ITEM_ENTITY.NAME, values);
    }

    /**
     * Fetch records that have <code>type IN (values)</code>
     */
    public List<com.platform.chorus.db.tables.pojos.ItemEntity> fetchByType(String... values) {
        return fetch(ItemEntity.ITEM_ENTITY.TYPE, values);
    }

    /**
     * Fetch records that have <code>creator IN (values)</code>
     */
    public List<com.platform.chorus.db.tables.pojos.ItemEntity> fetchByCreator(String... values) {
        return fetch(ItemEntity.ITEM_ENTITY.CREATOR, values);
    }

    /**
     * Fetch records that have <code>tags IN (values)</code>
     */
    public List<com.platform.chorus.db.tables.pojos.ItemEntity> fetchByTags(String[]... values) {
        return fetch(ItemEntity.ITEM_ENTITY.TAGS, values);
    }

    /**
     * Fetch records that have <code>contains IN (values)</code>
     */
    public List<com.platform.chorus.db.tables.pojos.ItemEntity> fetchByContains(Integer[]... values) {
        return fetch(ItemEntity.ITEM_ENTITY.CONTAINS, values);
    }

    /**
     * Fetch records that have <code>description IN (values)</code>
     */
    public List<com.platform.chorus.db.tables.pojos.ItemEntity> fetchByDescription(String... values) {
        return fetch(ItemEntity.ITEM_ENTITY.DESCRIPTION, values);
    }
}
