/*
 * This file is generated by jOOQ.
*/
package com.platform.chorus.db.tables.daos;


import com.platform.chorus.db.tables.ItemValue;
import com.platform.chorus.db.tables.records.ItemValueRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ItemValueDao extends DAOImpl<ItemValueRecord, com.platform.chorus.db.tables.pojos.ItemValue, Integer> {

    /**
     * Create a new ItemValueDao without any configuration
     */
    public ItemValueDao() {
        super(ItemValue.ITEM_VALUE, com.platform.chorus.db.tables.pojos.ItemValue.class);
    }

    /**
     * Create a new ItemValueDao with an attached configuration
     */
    public ItemValueDao(Configuration configuration) {
        super(ItemValue.ITEM_VALUE, com.platform.chorus.db.tables.pojos.ItemValue.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(com.platform.chorus.db.tables.pojos.ItemValue object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.platform.chorus.db.tables.pojos.ItemValue> fetchById(Integer... values) {
        return fetch(ItemValue.ITEM_VALUE.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.platform.chorus.db.tables.pojos.ItemValue fetchOneById(Integer value) {
        return fetchOne(ItemValue.ITEM_VALUE.ID, value);
    }

    /**
     * Fetch records that have <code>owner IN (values)</code>
     */
    public List<com.platform.chorus.db.tables.pojos.ItemValue> fetchByOwner(Integer... values) {
        return fetch(ItemValue.ITEM_VALUE.OWNER, values);
    }

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    public List<com.platform.chorus.db.tables.pojos.ItemValue> fetchByName(String... values) {
        return fetch(ItemValue.ITEM_VALUE.NAME, values);
    }

    /**
     * Fetch records that have <code>type IN (values)</code>
     */
    public List<com.platform.chorus.db.tables.pojos.ItemValue> fetchByType(String... values) {
        return fetch(ItemValue.ITEM_VALUE.TYPE, values);
    }

    /**
     * Fetch records that have <code>value IN (values)</code>
     */
    public List<com.platform.chorus.db.tables.pojos.ItemValue> fetchByValue(String... values) {
        return fetch(ItemValue.ITEM_VALUE.VALUE, values);
    }
}
