/*
 * This file is generated by jOOQ.
*/
package com.platform.chorus.database.tables.records;


import com.platform.chorus.database.tables.MetaMethod;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MetaMethodRecord extends UpdatableRecordImpl<MetaMethodRecord> implements Record6<Integer, String, String, String, Integer, String> {

    private static final long serialVersionUID = 821570326;

    /**
     * Setter for <code>public.meta_method.mid</code>.
     */
    public void setMid(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.meta_method.mid</code>.
     */
    public Integer getMid() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.meta_method.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.meta_method.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.meta_method.result</code>.
     */
    public void setResult(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.meta_method.result</code>.
     */
    public String getResult() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.meta_method.argument</code>.
     */
    public void setArgument(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.meta_method.argument</code>.
     */
    public String getArgument() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.meta_method.owner</code>.
     */
    public void setOwner(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.meta_method.owner</code>.
     */
    public Integer getOwner() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>public.meta_method.description</code>.
     */
    public void setDescription(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.meta_method.description</code>.
     */
    public String getDescription() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, String, String, String, Integer, String> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, String, String, String, Integer, String> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return MetaMethod.META_METHOD.MID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return MetaMethod.META_METHOD.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return MetaMethod.META_METHOD.RESULT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return MetaMethod.META_METHOD.ARGUMENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return MetaMethod.META_METHOD.OWNER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return MetaMethod.META_METHOD.DESCRIPTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getMid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getResult();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getArgument();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component5() {
        return getOwner();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getMid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getResult();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getArgument();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getOwner();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MetaMethodRecord value1(Integer value) {
        setMid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MetaMethodRecord value2(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MetaMethodRecord value3(String value) {
        setResult(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MetaMethodRecord value4(String value) {
        setArgument(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MetaMethodRecord value5(Integer value) {
        setOwner(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MetaMethodRecord value6(String value) {
        setDescription(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MetaMethodRecord values(Integer value1, String value2, String value3, String value4, Integer value5, String value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MetaMethodRecord
     */
    public MetaMethodRecord() {
        super(MetaMethod.META_METHOD);
    }

    /**
     * Create a detached, initialised MetaMethodRecord
     */
    public MetaMethodRecord(Integer mid, String name, String result, String argument, Integer owner, String description) {
        super(MetaMethod.META_METHOD);

        set(0, mid);
        set(1, name);
        set(2, result);
        set(3, argument);
        set(4, owner);
        set(5, description);
    }
}
