/*
 * This file is generated by jOOQ.
*/
package com.platform.chorus.database.tables.records;


import com.platform.chorus.database.tables.MetaField;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MetaFieldRecord extends UpdatableRecordImpl<MetaFieldRecord> implements Record10<Integer, String, String, Integer, String, String, String, Boolean, String, String> {

    private static final long serialVersionUID = 1383462147;

    /**
     * Setter for <code>public.meta_field.fid</code>.
     */
    public void setFid(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.meta_field.fid</code>.
     */
    public Integer getFid() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.meta_field.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.meta_field.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.meta_field.type</code>.
     */
    public void setType(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.meta_field.type</code>.
     */
    public String getType() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.meta_field.owner</code>.
     */
    public void setOwner(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.meta_field.owner</code>.
     */
    public Integer getOwner() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>public.meta_field.default</code>.
     */
    public void setDefault(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.meta_field.default</code>.
     */
    public String getDefault() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.meta_field.unit</code>.
     */
    public void setUnit(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.meta_field.unit</code>.
     */
    public String getUnit() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.meta_field.range</code>.
     */
    public void setRange(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.meta_field.range</code>.
     */
    public String getRange() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.meta_field.optional</code>.
     */
    public void setOptional(Boolean value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.meta_field.optional</code>.
     */
    public Boolean getOptional() {
        return (Boolean) get(7);
    }

    /**
     * Setter for <code>public.meta_field.format</code>.
     */
    public void setFormat(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.meta_field.format</code>.
     */
    public String getFormat() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.meta_field.description</code>.
     */
    public void setDescription(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.meta_field.description</code>.
     */
    public String getDescription() {
        return (String) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Integer, String, String, Integer, String, String, String, Boolean, String, String> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Integer, String, String, Integer, String, String, String, Boolean, String, String> valuesRow() {
        return (Row10) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return MetaField.META_FIELD.FID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return MetaField.META_FIELD.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return MetaField.META_FIELD.TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return MetaField.META_FIELD.OWNER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return MetaField.META_FIELD.DEFAULT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return MetaField.META_FIELD.UNIT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return MetaField.META_FIELD.RANGE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field8() {
        return MetaField.META_FIELD.OPTIONAL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return MetaField.META_FIELD.FORMAT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return MetaField.META_FIELD.DESCRIPTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getFid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getOwner();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getDefault();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getUnit();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getRange();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component8() {
        return getOptional();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getFormat();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component10() {
        return getDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getFid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getOwner();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getDefault();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getUnit();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getRange();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value8() {
        return getOptional();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getFormat();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MetaFieldRecord value1(Integer value) {
        setFid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MetaFieldRecord value2(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MetaFieldRecord value3(String value) {
        setType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MetaFieldRecord value4(Integer value) {
        setOwner(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MetaFieldRecord value5(String value) {
        setDefault(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MetaFieldRecord value6(String value) {
        setUnit(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MetaFieldRecord value7(String value) {
        setRange(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MetaFieldRecord value8(Boolean value) {
        setOptional(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MetaFieldRecord value9(String value) {
        setFormat(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MetaFieldRecord value10(String value) {
        setDescription(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MetaFieldRecord values(Integer value1, String value2, String value3, Integer value4, String value5, String value6, String value7, Boolean value8, String value9, String value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MetaFieldRecord
     */
    public MetaFieldRecord() {
        super(MetaField.META_FIELD);
    }

    /**
     * Create a detached, initialised MetaFieldRecord
     */
    public MetaFieldRecord(Integer fid, String name, String type, Integer owner, String default_, String unit, String range, Boolean optional, String format, String description) {
        super(MetaField.META_FIELD);

        set(0, fid);
        set(1, name);
        set(2, type);
        set(3, owner);
        set(4, default_);
        set(5, unit);
        set(6, range);
        set(7, optional);
        set(8, format);
        set(9, description);
    }
}
