/*
 * This file is generated by jOOQ.
*/
package com.platform.chorus.database.tables.records;


import com.platform.chorus.database.tables.MetaRelation;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MetaRelationRecord extends TableRecordImpl<MetaRelationRecord> implements Record3<String, Integer, Integer> {

    private static final long serialVersionUID = 1937053022;

    /**
     * Setter for <code>public.meta_relation.type</code>.
     */
    public void setType(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.meta_relation.type</code>.
     */
    public String getType() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.meta_relation.sid</code>.
     */
    public void setSid(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.meta_relation.sid</code>.
     */
    public Integer getSid() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.meta_relation.tid</code>.
     */
    public void setTid(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.meta_relation.tid</code>.
     */
    public Integer getTid() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<String, Integer, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<String, Integer, Integer> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return MetaRelation.META_RELATION.TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return MetaRelation.META_RELATION.SID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return MetaRelation.META_RELATION.TID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getSid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getTid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getSid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getTid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MetaRelationRecord value1(String value) {
        setType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MetaRelationRecord value2(Integer value) {
        setSid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MetaRelationRecord value3(Integer value) {
        setTid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MetaRelationRecord values(String value1, Integer value2, Integer value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MetaRelationRecord
     */
    public MetaRelationRecord() {
        super(MetaRelation.META_RELATION);
    }

    /**
     * Create a detached, initialised MetaRelationRecord
     */
    public MetaRelationRecord(String type, Integer sid, Integer tid) {
        super(MetaRelation.META_RELATION);

        set(0, type);
        set(1, sid);
        set(2, tid);
    }
}
