/*
 * This file is generated by jOOQ.
*/
package com.platform.chorus.database.tables.records;


import com.platform.chorus.database.tables.MetaClass;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MetaClassRecord extends UpdatableRecordImpl<MetaClassRecord> implements Record7<Integer, String, String, Integer[], String, String, String> {

    private static final long serialVersionUID = 1198873785;

    /**
     * Setter for <code>public.meta_class.cid</code>.
     */
    public void setCid(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.meta_class.cid</code>.
     */
    public Integer getCid() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.meta_class.package</code>.
     */
    public void setPackage(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.meta_class.package</code>.
     */
    public String getPackage() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.meta_class.name</code>.
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.meta_class.name</code>.
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.meta_class.extends</code>.
     */
    public void setExtends(Integer... value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.meta_class.extends</code>.
     */
    public Integer[] getExtends() {
        return (Integer[]) get(3);
    }

    /**
     * Setter for <code>public.meta_class.modifier</code>.
     */
    public void setModifier(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.meta_class.modifier</code>.
     */
    public String getModifier() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.meta_class.scope</code>.
     */
    public void setScope(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.meta_class.scope</code>.
     */
    public String getScope() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.meta_class.description</code>.
     */
    public void setDescription(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.meta_class.description</code>.
     */
    public String getDescription() {
        return (String) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, String, String, Integer[], String, String, String> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, String, String, Integer[], String, String, String> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return MetaClass.META_CLASS.CID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return MetaClass.META_CLASS.PACKAGE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return MetaClass.META_CLASS.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer[]> field4() {
        return MetaClass.META_CLASS.EXTENDS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return MetaClass.META_CLASS.MODIFIER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return MetaClass.META_CLASS.SCOPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return MetaClass.META_CLASS.DESCRIPTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getCid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getPackage();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer[] component4() {
        return getExtends();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getModifier();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getScope();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getCid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getPackage();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer[] value4() {
        return getExtends();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getModifier();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getScope();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MetaClassRecord value1(Integer value) {
        setCid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MetaClassRecord value2(String value) {
        setPackage(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MetaClassRecord value3(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MetaClassRecord value4(Integer... value) {
        setExtends(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MetaClassRecord value5(String value) {
        setModifier(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MetaClassRecord value6(String value) {
        setScope(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MetaClassRecord value7(String value) {
        setDescription(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MetaClassRecord values(Integer value1, String value2, String value3, Integer[] value4, String value5, String value6, String value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MetaClassRecord
     */
    public MetaClassRecord() {
        super(MetaClass.META_CLASS);
    }

    /**
     * Create a detached, initialised MetaClassRecord
     */
    public MetaClassRecord(Integer cid, String package_, String name, Integer[] extends_, String modifier, String scope, String description) {
        super(MetaClass.META_CLASS);

        set(0, cid);
        set(1, package_);
        set(2, name);
        set(3, extends_);
        set(4, modifier);
        set(5, scope);
        set(6, description);
    }
}
