openapi: 3.0.1
info:
  title: ChorusSystem
  description: chorus api document
  version: 1.0.0
servers:
- url: ///v2
tags:
- name: meta-class
  description: ""
- name: meta-field
  description: ""
- name: meta-method
  description: ""
- name: item-instance
  description: ""
paths:
  /class/{cid}/overview:
    get:
      tags:
      - meta-class
      summary: get class overview by id
      description: get class overview by id
      operationId: getClassOverviewById
      parameters:
      - name: cid
        in: path
        description: ID of class
        required: true
        schema:
          type: integer
          format: int32
      
      responses:
        200:
          description: return class list
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/SuccessResponseBody'
                - type: object
                  required:
                  - rootCause
                  properties:
                    result:
                      $ref: '#/components/schemas/ClassMember'
        500:
          description: System internal error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseBody'

  /classes/overview:
    get:
      tags:
      - meta-class
      summary: get meta classes overview with parameters
      description: get meta classes overview with parameters
      operationId: getClassesOverview
      parameters:
      - name: limit
        in: query
        description: class number limit
        schema:
          type: integer
          format: int32
      - name: offset
        in: query
        description: class number offset
        schema:
          type: integer
          format: int32
      - name: package
        in: query
        description: class package string pattern
        schema:
          type: string
      - name: name
        in: query
        description: class name string pattern
        schema:
          type: string

      responses:
        200:
          description: return class list
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/SuccessResponseBody'
                - type: object
                  required:
                  - rootCause
                  properties:
                    result: 
                      type: array
                      items:
                        $ref: '#/components/schemas/ClassMember'
        500:
          description: System internal error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseBody'

    post:
      tags:
      - meta-class
      summary: get all meta classes overview with request body
      description: get all meta classes overview  with request body
      operationId: getClassesOverviewWithBody
      requestBody:
        content: 
          'application/json':
            schema: 
              type: array
              items:
                type: integer
                format: int32

      responses:
        200:
          description: return class list
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/SuccessResponseBody'
                - type: object
                  required:
                  - rootCause
                  properties:
                    result: 
                      type: array
                      items:
                        $ref: '#/components/schemas/ClassMember'
        500:
          description: System internal error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseBody'  
  
  /classes:
    post:
      tags:
      - meta-class
      summary: create new meta class
      description: create new meta class
      operationId: createMetaClass
      requestBody:
        description: class array
        content:
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/SuccessResponseBody'
              - type: object
                required:
                - rootCause
                properties:
                  result: 
                    type: array
                    items:
                      $ref: '#/components/schemas/MetaClass'
        required: true
      responses:
        200:
          description: success
          content: {}
        500:
          description: System internal error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpError'
  /fields:
    get:
      tags:
      - meta-field
      summary: get all fields
      description: get all fields
      operationId: getFields
      responses:
        200:
          description: return field list
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/FieldMember'
        500:
          description: System internal error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpError'
  /methods:
    get:
      tags:
      - meta-method
      summary: get all methods
      description: get all methods
      operationId: getMethods
      responses:
        200:
          description: return field list
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MethodMember'
        500:
          description: System internal error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HttpError'
components:
  schemas:
    ClassMember:
      type: object
      properties:
        cid:
          type: integer
          format: int32
        package:
          type: string
        name:
          type: string
        modifier:
          type: string
        scope:
          type: string
        description:
          type: string
    MetaClass:
      type: object
      properties:
        class:
          $ref: '#/components/schemas/ClassMember'
        fields:
          type: array
          items:
            $ref: '#/components/schemas/FieldMember'
        methods:
          type: array
          items:
            $ref: '#/components/schemas/MethodMember'
    MethodMember:
      type: object
      properties:
        mid:
          type: integer
          format: int32
        name:
          type: string
        result:
          type: string
        argument:
          type: string
        owner:
          type: integer
          format: int32
        description:
          type: string
    FieldMember:
      type: object
      properties:
        fid:
          type: integer
          format: int32
        name:
          type: string
        type:
          type: string
        owner:
          type: integer
          format: int32
        default:
          type: string
        unit:
          type: string
        range:
          type: string
        optional:
          type: boolean
        format:
          type: string
        description:
          type: string
    HttpError:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
    ResponseBody:
      type: object
      properties:
        message:
          type: string
    ErrorResponseBody:
      allOf:
      - $ref: '#/components/schemas/ResponseBody'
      - type: object
        properties:
          cause:
            type: string
          code:
            type: integer
            format: int32
    SuccessResponseBody:
      allOf:
      - $ref: '#/components/schemas/ResponseBody'
      - type: object
        properties:
          result: 
            type: object
        
