openapi: 3.0.1
info:
  title: ChorusPlatform
  description: chorus api document
  version: 1.0.0
servers:
- url: ///v2
tags:
- name: meta-class
  description: ""
- name: meta-field
  description: ""
- name: meta-method
  description: ""
- name: item-instance
  description: ""
paths:
  /class/meta:
    get:
      tags:
      - meta-class
      summary: get class meta detail by id
      description: get class meta detail by id
      operationId: getClassMeta
      parameters:
      - name: cid
        in: query
        description: ID of class
        required: true
        schema:
          type: integer
          format: int32
      
      responses:
        200:
          description: return class meta
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/SuccessResponseBody'
                - type: object
                  properties:
                    result:
                      $ref: '#/components/schemas/ClassMeta'
        500:
          description: System internal error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseBody'
     
    post:
      tags:
      - meta-class
      summary: create new meta class
      description: create new meta class
      operationId: createMetaClass
      requestBody:
        description: class array
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ClassMeta'
        required: true
        
      responses:
        200:
          description: return class cid 
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/SuccessResponseBody'
                - type: object
                  properties:
                    cid:
                      type: integer
                      format: int32
        500:
          description: System internal error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseBody' 

  /class/overview:
    get:
      tags:
      - meta-class
      summary: get class overview by id
      description: get class overview by id
      operationId: getClassOverviewById
      parameters:
      - name: cid
        in: query
        description: ID of class
        required: true
        schema:
          type: integer
          format: int32
      
      responses:
        200:
          description: return class list
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/SuccessResponseBody'
                - type: object
                  properties:
                    result:
                      $ref: '#/components/schemas/ClassMember'
        500:
          description: System internal error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseBody'

  /class/overview/list:
    get:
      tags:
      - meta-class
      summary: get meta classes overview with parameters
      description: get meta classes overview with parameters
      operationId: getClassesOverview
      parameters:
      - name: limit
        in: query
        description: class number limit
        schema:
          type: integer
          format: int32
      - name: offset
        in: query
        description: class number offset
        schema:
          type: integer
          format: int32
      - name: package
        in: query
        description: class package string pattern
        schema:
          type: string
      - name: name
        in: query
        description: class name string pattern
        schema:
          type: string

      responses:
        200:
          description: return class list
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/SuccessResponseBody'
                - type: object
                  properties:
                    result: 
                      type: array
                      items:
                        $ref: '#/components/schemas/ClassMember'
        500:
          description: System internal error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseBody'

    post:
      tags:
      - meta-class
      summary: get all meta classes overview with request body
      description: get all meta classes overview  with request body
      operationId: getClassesOverviewWithBody
      requestBody:
        description: class id list
        content: 
          'application/json':
            schema: 
              type: array
              items:
                type: integer
                format: int32
                

      responses:
        200:
          description: return class list
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/SuccessResponseBody'
                - type: object
                  properties:
                    result: 
                      type: array
                      items:
                        $ref: '#/components/schemas/ClassMember'
        500:
          description: System internal error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseBody'  
  
  /class/meta/list:
    post:
      tags:
      - meta-class
      summary: create new meta class
      description: create new meta class
      operationId: createMetaClasses
      requestBody:
        description: class array
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/ClassMeta'
        required: true
      responses:
        200:
          description: return success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponseBody'

        500:
          description: System internal error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseBody'
  /field/list:
    get:
      tags:
      - meta-field
      summary: get all fields by given parameters
      description: get all fields given parameters
      operationId: getFields
      parameters:
      - name: limit
        in: query
        description: field number limit
        schema:
          type: integer
          format: int32
      - name: offset
        in: query
        description: field number offset
        schema:
          type: integer
          format: int32
      - name: owner
        in: query
        description: field owner id
        schema:
          type: integer
          format: int32
      - name: name
        in: query
        description: field name string pattern
        schema:
          type: string
      - name: type
        in: query
        description: field type = class package + class name  matching pattern string
        schema:
          type: string
      - name: description
        in: query
        description: field description matching pattern string
        schema:
          type: string
        
      responses:
        200:
          description: return field list
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/SuccessResponseBody'
                - type: object
                  properties:
                    result: 
                      type: array
                      items:
                        $ref: '#/components/schemas/FieldMember'
        500:
          description: System internal error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseBody'
  /methods:
    get:
      tags:
      - meta-method
      summary: get all methods by given parameters
      description: get all methods by given parameters
      operationId: getMethods
      parameters:
      - name: limit
        in: query
        description: field number limit
        schema:
          type: integer
          format: int32
      - name: offset
        in: query
        description: field number offset
        schema:
          type: integer
          format: int32
      - name: owner
        in: query
        description: field owner id
        schema:
          type: integer
          format: int32
      - name: name
        in: query
        description: field name string pattern
        schema:
          type: string
      - name: result
        in: query
        description: field type = class package + class name  matching pattern string
        schema:
          type: string
      - name: argument
        in: query
        description: field description matching pattern string
        schema:
          type: string
      - name: description
        in: query
        description: field description matching pattern string
        schema:
          type: string    
      
        
      responses:
        200:
          description: return field list
          content:
            application/json:
              schema:
                allOf:
                - $ref: '#/components/schemas/SuccessResponseBody'
                - type: object
                  properties:
                    result: 
                      type: array
                      items:
                        $ref: '#/components/schemas/FieldMember'
        500:
          description: System internal error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponseBody'
components:
  schemas:
    ClassMember:
      type: object
      properties:
        cid:
          type: integer
          format: int32
        package:
          type: string
        name:
          type: string
        modifier:
          type: string
        scope:
          type: string
        description:
          type: string
    ClassMeta:
      type: object
      properties:
        class:
          $ref: '#/components/schemas/ClassMember'
        fields:
          type: array
          items:
            $ref: '#/components/schemas/FieldMember'
        methods:
          type: array
          items:
            $ref: '#/components/schemas/MethodMember'
    MethodMember:
      type: object
      properties:
        mid:
          type: integer
          format: int32
        name:
          type: string
        result:
          type: string
        argument:
          type: string
        owner:
          type: integer
          format: int32
        description:
          type: string
    FieldMember:
      type: object
      properties:
        fid:
          type: integer
          format: int32
        name:
          type: string
        type:
          type: string
        owner:
          type: integer
          format: int32
        default:
          type: string
        unit:
          type: string
        range:
          type: string
        optional:
          type: boolean
        format:
          type: string
        description:
          type: string
    HttpError:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
    ResponseBody:
      type: object
      properties:
        message:
          type: string
    ErrorResponseBody:
      allOf:
      - $ref: '#/components/schemas/ResponseBody'
      - type: object
        properties:
          cause:
            type: string
          code:
            type: integer
            format: int32
    SuccessResponseBody:
      allOf:
      - $ref: '#/components/schemas/ResponseBody'
      - type: object
        properties:
          result: 
            type: object
        
