/*
 * This file is generated by jOOQ.
*/
package com.platform.chorus.database;


import com.platform.chorus.database.tables.ItemInstance;
import com.platform.chorus.database.tables.MetaClass;
import com.platform.chorus.database.tables.MetaField;
import com.platform.chorus.database.tables.MetaMethod;
import com.platform.chorus.database.tables.records.ItemInstanceRecord;
import com.platform.chorus.database.tables.records.MetaClassRecord;
import com.platform.chorus.database.tables.records.MetaFieldRecord;
import com.platform.chorus.database.tables.records.MetaMethodRecord;

import javax.annotation.Generated;

import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<ItemInstanceRecord, Integer> IDENTITY_ITEM_INSTANCE = Identities0.IDENTITY_ITEM_INSTANCE;
    public static final Identity<MetaClassRecord, Integer> IDENTITY_META_CLASS = Identities0.IDENTITY_META_CLASS;
    public static final Identity<MetaFieldRecord, Integer> IDENTITY_META_FIELD = Identities0.IDENTITY_META_FIELD;
    public static final Identity<MetaMethodRecord, Integer> IDENTITY_META_METHOD = Identities0.IDENTITY_META_METHOD;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<ItemInstanceRecord> CI_OBJECTS_PKEY = UniqueKeys0.CI_OBJECTS_PKEY;
    public static final UniqueKey<MetaClassRecord> META_CLASSES_PKEY = UniqueKeys0.META_CLASSES_PKEY;
    public static final UniqueKey<MetaClassRecord> CL_U_KEY = UniqueKeys0.CL_U_KEY;
    public static final UniqueKey<MetaFieldRecord> META_FIELDS_PKEY = UniqueKeys0.META_FIELDS_PKEY;
    public static final UniqueKey<MetaFieldRecord> FD_U_KEY = UniqueKeys0.FD_U_KEY;
    public static final UniqueKey<MetaMethodRecord> META_METHODS_PKEY = UniqueKeys0.META_METHODS_PKEY;
    public static final UniqueKey<MetaMethodRecord> MT_U_KEY = UniqueKeys0.MT_U_KEY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<ItemInstanceRecord, Integer> IDENTITY_ITEM_INSTANCE = Internal.createIdentity(ItemInstance.ITEM_INSTANCE, ItemInstance.ITEM_INSTANCE.OID);
        public static Identity<MetaClassRecord, Integer> IDENTITY_META_CLASS = Internal.createIdentity(MetaClass.META_CLASS, MetaClass.META_CLASS.CID);
        public static Identity<MetaFieldRecord, Integer> IDENTITY_META_FIELD = Internal.createIdentity(MetaField.META_FIELD, MetaField.META_FIELD.FID);
        public static Identity<MetaMethodRecord, Integer> IDENTITY_META_METHOD = Internal.createIdentity(MetaMethod.META_METHOD, MetaMethod.META_METHOD.MID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<ItemInstanceRecord> CI_OBJECTS_PKEY = Internal.createUniqueKey(ItemInstance.ITEM_INSTANCE, "ci_objects_pkey", ItemInstance.ITEM_INSTANCE.OID);
        public static final UniqueKey<MetaClassRecord> META_CLASSES_PKEY = Internal.createUniqueKey(MetaClass.META_CLASS, "meta_classes_pkey", MetaClass.META_CLASS.CID);
        public static final UniqueKey<MetaClassRecord> CL_U_KEY = Internal.createUniqueKey(MetaClass.META_CLASS, "cl_u_key", MetaClass.META_CLASS.PACKAGE, MetaClass.META_CLASS.NAME);
        public static final UniqueKey<MetaFieldRecord> META_FIELDS_PKEY = Internal.createUniqueKey(MetaField.META_FIELD, "meta_fields_pkey", MetaField.META_FIELD.FID);
        public static final UniqueKey<MetaFieldRecord> FD_U_KEY = Internal.createUniqueKey(MetaField.META_FIELD, "fd_u_key", MetaField.META_FIELD.OWNER, MetaField.META_FIELD.NAME);
        public static final UniqueKey<MetaMethodRecord> META_METHODS_PKEY = Internal.createUniqueKey(MetaMethod.META_METHOD, "meta_methods_pkey", MetaMethod.META_METHOD.MID);
        public static final UniqueKey<MetaMethodRecord> MT_U_KEY = Internal.createUniqueKey(MetaMethod.META_METHOD, "mt_u_key", MetaMethod.META_METHOD.OWNER, MetaMethod.META_METHOD.NAME);
    }
}
