/*
 * This file is generated by jOOQ.
*/
package com.platform.chorus.database;


import com.platform.chorus.database.tables.ItemInstance;
import com.platform.chorus.database.tables.MetaClass;
import com.platform.chorus.database.tables.MetaField;
import com.platform.chorus.database.tables.MetaMethod;
import com.platform.chorus.database.tables.MetaRelation;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.item_instance</code>.
     */
    public static final ItemInstance ITEM_INSTANCE = com.platform.chorus.database.tables.ItemInstance.ITEM_INSTANCE;

    /**
     * The table <code>public.meta_class</code>.
     */
    public static final MetaClass META_CLASS = com.platform.chorus.database.tables.MetaClass.META_CLASS;

    /**
     * The table <code>public.meta_field</code>.
     */
    public static final MetaField META_FIELD = com.platform.chorus.database.tables.MetaField.META_FIELD;

    /**
     * The table <code>public.meta_method</code>.
     */
    public static final MetaMethod META_METHOD = com.platform.chorus.database.tables.MetaMethod.META_METHOD;

    /**
     * The table <code>public.meta_relation</code>.
     */
    public static final MetaRelation META_RELATION = com.platform.chorus.database.tables.MetaRelation.META_RELATION;
}
